---
title: "R Notebook"
output: html_notebook
---

```{r}
require(readr)
require(rstanarm)
require(broom)
```

```{r}
# download csv, and write to local disk...
songs <- read_csv('https://assets.datacamp.com/production/repositories/2199/datasets/3c921f85674c92085b3428c303b9364573a8bd4f/datacamp-spotify-data.csv')
write_csv(songs, './songs.csv')
songs <- read_csv('songs.csv')
```

```{r}
# data prep
lm_model <- lm(popularity ~ song_age, data=songs)
lm_summary <- summary(lm_model)
lm_summary
```

```{r}
# Print the R-squared from the linear model
lm_summary$r.squared

# Calulate sums of squares
ss_res <- var(residuals(lm_model))
ss_fit <- var(fitted(lm_model))

# Calculate the R-squared
1 - (ss_res / (ss_res + ss_fit))
```

```{r}
# data prep
stan_model <- stan_glm(popularity ~ song_age, data=songs)
summary(stan_model)
```

```{r}
# Save the variance of residulas
ss_res <- var(residuals(stan_model))

# Save the variance of fitted values
ss_fit <- var(fitted(stan_model))

# Calculate the R-squared
1 - (ss_res / (ss_res + ss_fit))
```

```{r}
# Calculate posterior predictive scores
predictions <- posterior_linpred(stan_model)

# Print a summary of the observed data
summary(songs$popularity)

# Print a summary of the 1st replication
summary(predictions[1,])

# Print a summary of the 10th replication
summary(predictions[10,])
```

```{r}
# Calculate the posterior distribution of the R-squared
r2_posterior <- bayes_R2(stan_model)

# Make a histogram of the distribution
hist(r2_posterior)
```

```{r}
# Create density comparison
pp_check(stan_model, "dens_overlay")

# Create scatter plot of means and standard deviations
pp_check(stan_model, "stat_2d")
```

```{r}
install.packages("loo")
require(loo)
```

```{r}
require(rstanarm)
loo(stan_model, cores=8)

# Estimate the model with 1 predictor
model_1pred <- stan_glm(popularity ~ song_age, data = songs)

# Print the LOO estimate for the 1 predictor model
loo(model_1pred)

# Estimate the model with both predictors
model_2pred <- stan_glm(popularity ~ song_age * artist_name, data = songs)

# Print the LOO estimates for the 2 predictor model
loo(model_2pred)
```

```{r}
# positive = second model is better
# difference is > standard error = even though the model is more complicated, it is worth if for the better result.
compare(loo(model_1pred), loo(model_2pred))
```







