---
title: "R Notebook"
output: html_notebook
---

# Chapter 4 notes

```{r}
# Build the null model with rpart()
Runners$all_the_same <- 1 # null "explanatory" variable
null_model <- rpart(start_position ~ all_the_same, data = Runners)

# Evaluate the null model on training data
null_model_output <- evaluate_model(null_model, data = Runners, type = "class")

# Calculate the error rate
with(data = null_model_output, mean(start_position != model_output, na.rm = TRUE))

# Generate a random guess...
null_model_output$random_guess <- mosaic::shuffle(Runners$start_position)

# ...and find the error rate
with(data = null_model_output, mean(start_position != random_guess, na.rm = TRUE))
```

```{r paged.print=FALSE}
head(null_model_output[,c("start_position", "model_output", "random_guess")], n=20)
```


```{r}
# Train the model
model <- rpart(start_position ~ age + sex, data = Runners, cp = 0.001)

# Get model output with the training data as input
model_output <- evaluate_model(model, data = Runners, type = "class")

# Find the error rate
with(data = model_output, mean(start_position != model_output, na.rm = TRUE))
```

```{r}
# data prep
df <- Runners[(!is.na(Runners$start_position) & !is.na(Runners$net)), ]
Training_data <- df[1:102,]
Testing_data <- df[1000:1098,]

# Train the models 
null_model <- rpart(start_position ~ all_the_same,
                    data = Training_data, cp = 0.001)
model_1 <- rpart(start_position ~ age, 
                 data = Training_data, cp = 0.001)
model_2 <- rpart(start_position ~ age + sex, 
                 data = Training_data, cp = 0.001)
model_3 <- rpart(start_position ~ net + sex + age, 
                 data = Training_data, cp = 0.001)

# Find the out-of-sample error rate
null_output    <- evaluate_model(null_model, data = Testing_data, type = "class")
model_1_output <- evaluate_model(model_1, data = Testing_data, type = "class")
model_2_output <- evaluate_model(model_2, data = Testing_data, type = "class")
model_3_output <- evaluate_model(model_3, data = Testing_data, type = "class")

# Calculate the error rates
null_rate    <- with(data = null_output, 
                  mean(start_position != model_output, na.rm = TRUE))
model_1_rate <- with(data = model_1_output, 
                  mean(start_position != model_output, na.rm = TRUE))
model_2_rate <- with(data = model_2_output, 
                  mean(start_position != model_output, na.rm = TRUE))
model_3_rate <- with(data = model_3_output, 
                  mean(start_position != model_output, na.rm = TRUE))

# Display the error rates
null_rate
model_1_rate
model_2_rate
model_3_rate
```
Interesting - I thought the time would map most to the starting position! It doesn't! And the null model is one of the best predictors of all on my training set... nashing of teeth... just goes to show you need to test your model with mental data to know if your hypothesis are worth jack shit.

```{r}
library(rpart)
# play with low complexity
model_2 <- rpart(net ~ age + sex, data = Runners, cp = 0.01)
rpart.plot::prp(model_2, type = 3)

# play with high complexity
model_2 <- rpart(net ~ age + sex, data = Runners, cp = 0.001)
rpart.plot::prp(model_2, type = 3)

# what is net for 58 year old female = 98
```

```{r}
data("Birth_weight")

model_1 <- rpart(baby_wt ~ smoke + income, 
                 data = Birth_weight)
model_2 <- rpart(baby_wt ~ mother_age + mother_wt, 
                 data = Birth_weight)
model_3 <- rpart(baby_wt ~ mother_age + mother_wt + smoke + income, 
                 data = Birth_weight)

rpart.plot::prp(model_1, type = 3)
rpart.plot::prp(model_2, type = 3)
rpart.plot::prp(model_3, type = 3)
```

```{r}
model_all <- rpart(baby_wt ~ ., data = Birth_weight)
rpart.plot::prp(model_all, type = 3)

model_not_wt <- rpart(gestation ~ . - baby_wt, data = Birth_weight)
rpart.plot::prp(model_not_wt, type = 3)
```







