---
title: "R Notebook"
output: html_notebook
---

# Chapter 2

```{r}
library(pryr)

lapply(list("is.complex", "seq.Date", "is.na.data.frame", "sort", "order"), is_s3_generic)
lapply(list("is.complex", "seq.Date", "is.na.data.frame", "sort", "order"), is_s3_method)
```

```{r}
# data prep
#> cat(sleep$extra, sep=',')
extra <- c(0.7,-1.6,-0.2,-1.2,-0.1,3.4,3.7,0.8,0,2,1.9,0.8,1.1,0.1,-0.1,4.4,5.5,1.6,4.6,3.4)

# > cat(sleep$group, sep='", "', fill = T)
group <- c("1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2")

#> cat(sleep$ID, sep='", "', fill = T)
ID <- c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10")

sleep <- data_frame(extra = extra, group = group, ID = ID)
```

```{r}
# Create get_n_elements
get_n_elements <- function(x, ...) {
  UseMethod("get_n_elements")
}
```

```{r}
# View get_n_elements
get_n_elements

# Create a data.frame method for get_n_elements
get_n_elements.data.frame <- function(x, ...) {
  nrow(x) * ncol(x)
}

# Call the method on the sleep dataset
n_elements_sleep <- get_n_elements(sleep)

# View the result
n_elements_sleep
```

```{r}
# View pre-defined objects
ls.str()

# Create a default method for get_n_elements
get_n_elements.default <- function(x, ...) {
  length(unlist(x))
}

# Call the method on the ability.cov dataset
n_elements_ability.cov <- get_n_elements(ability.cov)
```

```{r}
# Find methods for print
methods(print)

# you can also check per classes
methods(class = data.frame)
```

The fastest parts of R are written in C, and the lowest level C interface in R is called primitives.

```{r}
# Here are some prmitive functions - notice backtick to stop if being evaluated.
`if`
`+`
exp

# List S3 functions that are written in C at primitive level
.S3PrimitiveGenerics

```

```{r}
# data prep
# > cat(hair$styles, sep='", "')
styles <- c("afro", "beehive", "crew cut", "mohawk", "mullet", "pony tail", "quiff")

# > cat(hair$colors, sep='", "')
colors <- c("black", "brown", "blonde", "ginger", "grey")

hair = list(colors = colors, styles = styles)

class(hair) <- "hairstylist"
```

```{r}
# View the structure of hair
str(hair)

# What primitive generics are available?
.S3PrimitiveGenerics

# Does length.hairstylist exist?
exists("length.hairstylist")

# What is the length of hair?
length(hair)
```

```{r}
methods("is.na")
```

```{r}
# Data prep
kitty <- "Miaow!"

# View the kitty
kitty

# Assign classes
class(kitty) <- c("cat", "mammal", "character")

# Does kitty inherit from cat/mammal/character vector?
inherits(kitty, 'cat')
inherits(kitty, 'mammal')
inherits(kitty, 'character')

# Is kitty a character vector?
is.character(kitty)

# Does kitty inherit from dog?
inherits(kitty, 'dog')
```

```{r}
# data prep
what_am_i <- function(x, ...)
{
  UseMethod("what_am_i")
}

# Inspect your workspace
ls.str()

# cat method
what_am_i.cat <- function(x, ...)
{
  # Write a message
  message("I'm a cat")
  # Call NextMethod
  NextMethod("mammal")
}

# mammal method
what_am_i.mammal <- function(x, ...) {
  message("I'm a mammal")
  NextMethod("character")
}

# character method
what_am_i.character <- function(x, ...) {
  message("I'm a character vector")
}

# Call what_am_i()
what_am_i(kitty)
```

