---
title: "Chapter 2"
output: html_notebook
---

```{r}
# data prep - load KNN library
install.packages("FNN")
require(FNN)
```

```{r}
# data prep - I downloaded red wine from kaggle. That looks closed in size
require(tidyverse)
wine_df <- read_csv('wineQualityReds.csv')
glimpse(wine_df)
wine <- wine_df %>% select(pH, alcohol)
glimpse(wine)
```

```{r}
# View the contents of the wine data
head(wine)

# Scatterplot of wine pH against alcohol
plot(pH ~ alcohol, data = wine)
```

```{r}
# Calculate the 5 nearest neighbors distance
wine_nn <- get.knn(wine, k = 5)

# View the distance matrix
head(wine_nn$nn.dist)
```

```{r}
# Calculate the 5 nearest neighbors distance
wine_nn <- get.knn(wine, k = 5)

# View the distance matrix
head(wine_nn$nn.dist)

# Distance from wine 5 to nearest neighbor
wine_nn$nn.dist[15, 1]

# Row index of wine 5's nearest neighbor 
wine_nn$nn.ind[15, 1]

# Return data for wine 5 and its nearest neighbor
wine[c(5, 325), ]
```

```{r}
# Calculate the 5 nearest neighbors distance
wine_nn <- get.knn(wine, k = 5)

# Create score by averaging distances
wine_nnd <- rowMeans(wine_nn$nn.dist)

# Print row index of the most anomalous point
which.max(wine_nnd)
```

```{r}
# Observe differences in column scales 
summary(wine)

# Standardize the wine columns
wine_scaled <- scale(wine)

# Observe standardized column scales
summary(wine_scaled)
```

```{r}
wine_nn <- get.knn(wine, k = 5)
wine_nnd <- wine_nn$nn.dist

# Print the 5-nearest neighbor distance score
wine_nnd[1:5]

# Add the score as a new column 
wine$score <- wine_nnd
```

```{r}
# Scatterplot showing pH, alcohol and kNN score
plot(pH ~ alcohol, wine, cex = sqrt(score), pch = 20)
```

```{r}
install.packages("dbscan")
require(dbscan)
```

```{r}
# Calculate the LOF for wine data
wine_lof <- lof(scale(wine), k=5)

# Append the LOF score as a new column
wine$score <- wine_lof
```

```{r}
# Scatterplot showing pH, alcohol and LOF score
plot(pH ~ alcohol, cex=score, pch=20, data=wine)
```

```{r}
# Scaled wine data
wine_scaled <- scale(wine[,1:2])

# Calculate and append kNN distance as a new column
wine_nn <- get.knn(wine_scaled, k = 10)
wine$score_knn <- rowMeans(wine_nn$nn.dist)     

# Calculate and append LOF as a new column
wine$score_lof <- lof(wine_scaled, k = 10)

# Find the row location of highest kNN
which.max(wine$score_knn)

# Find the row location of highest LOF
which.max(wine$score_lof)
```






