---
title: "Chapter 4"
output: html_notebook
---

```{r}

```



```{r}
# whoop - save df to csv text, then paste to local csv file
# write.table(thyroid, sep=',', quote=T, row.names=F)
thyroid <- read_csv('thyroid.csv')
str(thyroid)
```

```{r}
# View contents of thryoid data
head(thyroid)

# Tabulate the labels
table(thyroid$label)

# Proportion of thyroid cases
prop_disease <- 22/1000
```

```{r}
# Plot of TSH, T3 and labels
plot(TSH ~ T3, data = thyroid, pch = 20, col = label + 1)
```

```{r}
# Plot of TT4, TBG and labels
plot(TT4 ~ TBG, data = thyroid, pch = 20, col = label + 1)
```

```{r}
library(isofor)

# Fit isolation forest
thyroid_forest <- iForest(thyroid[,-1], nt = 200, multicore = T)

# Anomaly score 
thyroid$iso_score <- predict(thyroid_forest, newdata=thyroid[,-1])

# Boxplot of the anomaly score against labels
boxplot(iso_score ~ label, thyroid, col = "olivedrab4")
```

```{r}
library(dbscan)
thyroid_meas <- thyroid[,-c(1,8)]
iso_score <- thyroid$iso_score

# Create a LOF score for thyroid
lof_score <- lof(scale(thyroid_meas), k = 10)
                 
# Calculate high threshold for lof_score
high_lof <- quantile(lof_score, probs = 0.98) 

# Append binary LOF score to thyroid data
thyroid$binary_lof <- as.numeric(lof_score >= high_lof)
                 
# Calculate high threshold for iso_score
high_iso <- quantile(iso_score, probs = 0.98) 

# Append binary isolation score to thyroid data
thyroid$binary_iso <- as.numeric(iso_score > high_iso)         
```

```{r}
# Tabulate agreement of label and binary isolation score 
table(thyroid$label, thyroid$binary_iso)

# Tabulate agreement of label and binary LOF score 
table(thyroid$label, thyroid$binary_lof)

# Proportion of binary_iso and label that agree
iso_prop <- (970+12)/1000

# Proportion of binary_lof and label that agree
lof_prop <- (958+0)/1000
```

```{r}
table(thyroid$label, thyroid$binary_iso)
table(thyroid$label, thyroid$binary_lof)

# Precision for binary scores
precision_iso <- 11 / (9 + 11)
precision_lof <- 0 / (20 + 0)

# Recall for binary scores
recall_iso <- 11/22
recall_lof <- 0/22
```

```{r}
thyroid <- read_csv('thyroid_cat.csv')
summary(thyroid)
```

```{r}
# Print the column classes in thyroid
sapply(X = thyroid, FUN = class)

# Convert column with character class to factor
thyroid$age <- as.factor(thyroid$age)
thyroid$sex <- as.factor(thyroid$sex)

# Check that all columns are factor or numeric
sapply(X = thyroid, FUN = class)
```

```{r}
# Check the class of age column
class(thyroid$age)

# Check the class of sex column
class(thyroid$sex)

# Fit an isolation forest with 100 trees
thyroid_for <- iForest(thyroid[,-1], nt=100, multicore=T)
```

```{r}
require(cluster)

# Calculate Gower's distance matrix
thyroid_dist <- daisy(thyroid[,-1], metric = 'gower')

# Generate LOF scores for thyroid data
thyroid_lof <- lof(thyroid_dist, k = 10)

# Range of values in the distance matrix
range(as.matrix(thyroid_dist))
```







