---
title: "ch1"
output: html_notebook
---

# Chapter 1


```{r}
require(tidyverse)
```

```{r}
# Creating three 3's and four 4's, respectively
rep(3, 3)
rep(4, 4)

# Creating a vector with the first three even numbers and the first three odd numbers
seq(2, 6, by = 2)
seq(1, 5, by = 2)

# Re-creating the previous four vectors using the 'c' command
c(3, 3, 3)
c(4, 4, 4, 4)

c(2, 4, 6)
c(1, 3, 5)
```

```{r}
# data prep
x <- seq(1, 7, by=1)
y <- seq(2, 14, by=2)
z <- c(1, 1, 2)

# Add x to y and print
print(x + y)

# Multiply z by 2 and print
print(2 * z)

# Multiply x and y by each other and print
print(x * y)

# Add x to z, if possible, and print
print(x + z)
```

```{r}
# Data prep
A <- matrix(rep(1,4), 2, 2)

# Create a matrix of all 1's and all 2's that are 2 by 3 and 3 by 2, respectively
matrix(1, nrow = 2, ncol = 3)

print(matrix(2, nrow = 3, ncol = 2))

# Create a matrix B and changing the byrow designation.
B <- matrix(c(1, 2, 3, 2), nrow = 2, ncol = 2, byrow = FALSE)
B <- matrix(c(1, 2, 3, 2), nrow = 2, ncol = 2, byrow = TRUE)

# Add A to the previously-created matrix
A + B
```

```{r}
A = matrix(c(1, 2, 3, -1, 0, 3), nrow = 2, ncol = 3, byrow = TRUE)
A %*%c(1, 1, -1)
#A %*% c(-2, 2)
#A %*% c(2, -1, 3, 4, 7)
A% %*% c(-1, 2, 1, 3)
```

```{r}
A <- matrix(c(1,2,5,0,-1,3), nrow=3, ncol=2, byrow=TRUE)
B <- matrix(c(5,7,3,2,4,0), nrow=2, ncol=3, byrow=TRUE)
A
B
A%*%B
```

```{r}
A <- matrix(c(4,0,0,1), ncol=2, nrow=2, byrow=TRUE)
b <- c(1,1)
B <- matrix(c(1,0,0,(2.0/3.0)), ncol=2, nrow=2, byrow=TRUE)

# Multiply A by b on the left
A %*% b

# Multiply B by b on the left
B %*% b

```

```{r}
# data prep
A <- matrix(c(-1,0,0,1), ncol=2, nrow=2, byrow=TRUE)
B <- matrix(c(1,0,0-1), ncol=2, nrow=2, byrow=TRUE)
C <- matrix(c(-4,0,0,-2), ncol=2, nrow=2, byrow=TRUE)
b <- c(2,1)

# Multiply A by b on the left
A %*% b

# Multiplby B by b on the left
B %*% b

# Multiply C by b on the left
C %*% b
```

```{r}
A = matrix(c(1, 3, 2, -1, 0, 1), nrow = 2, ncol = 3)
B = matrix(c(-1, 1, 2, -3), nrow = 2, ncol = 2)

B %*% A
```

```{r}
# data prep
sin_45 = sin(0.25*pi)
A <- matrix(c(sin_45, -1*sin_45, sin_45, sin_45), nrow=2, ncol=2, byrow=TRUE)
B <- matrix(c(1, 0, 0, -1), nrow=2, ncol=2, byrow=TRUE)
c <- rep(1,2)

# Multiply A by B on the left
A%*%B

# Multiply A by B on the right
B%*%A

# Multiply b by B then A (on the left)
A%*%B%*%b

# Multiply b by A then B (on the left)
B%*%A%*%b

```


```{r}
# data prep
A <- matrix(c(1,2,-1,2), nrow=2, ncol=2, byrow=TRUE)


# Take the inverse of the 2 by 2 identity matrix
solve(diag(2))

# Take the inverse of the matrix A
Ainv <- solve(A)

# Multiply A by its inverse on the left
Ainv%*%A

# Multiply A by its inverse on the right
A%*%Ainv

```

