---
title: "xts and zoo"
output: html_notebook
---

# Chapter 5 

```{r}
temps

# View the first three indexes of temps
index(temps)[1:3]

# Get the index class of temps
indexClass(temps)

# Get the timezone of temps
indexTZ(temps)

# Change the format of the time display
indexFormat(temps) <- "%b-%d-%Y"

# View the new format
head(temps)
```

```{r}
# prep data
times <- c(
  "2018-01-01 01:26:03 GMT", "2018-01-01 01:27:43 GMT",
   "2018-01-01 01:29:23 GMT", "2018-01-01 01:31:03 GMT",
   "2018-01-01 01:32:43 GMT", "2018-01-01 01:34:23 GMT",
   "2018-01-01 01:36:03 GMT", "2018-01-01 01:37:43 GMT",
   "2018-01-01 01:39:23 GMT", "2018-01-01 01:41:03 GMT")
times <- as.POSIXct(times)

# Construct times_xts with tzone set to America/Chicago
times_xts <- xts(1:10, order.by = times, tzone = "America/Chicago")

# Change the time zone of times_xts to Asia/Hong_Kong
tzone(times_xts) <- "Asia/Hong_Kong"
  
# Extract the current time zone of times_xts
tzone(times_xts)
```

```{r}
# Calculate the periodicity of temps
periodicity(temps)

# Calculate the periodicity of edhec
periodicity(edhec)

# Convert edhec to yearly
edhec_yearly <- to.yearly(edhec)

# Calculate the periodicity of edhec_yearly
periodicity(edhec_yearly)
```

```{r}
# Count the months
nmonths(edhec)

# Count the quarters
nquarters(edhec)

# Count the years
nyears(edhec)

```

```{r}
# Explore underlying units of temps in two commands: .index() and .indexwday()
.index(temps)
.indexwday(temps)

# Create an index of weekend days using which()
index <- which(.indexwday(temps) == "0" | .indexwday(temps) == "6")

# Select the index
temps[index]
```

```{r}
# prep data... mot finished...
z <- as.xts(as.matrix(read.zoo("z.tsv", index.column = 0), ncol = 1))

# Make z have unique timestamps
z_unique <- make.index.unique(z, eps = 1e-4)

# Remove duplicate times in z
z_dup <- make.index.unique(z, drop = TRUE)

# Round observations in z to the next hour
z_round <- align.time(z, n = 3600)




```

