---
title: "Machine Learning Toolbox"
output: html_notebook
---

```{r}
data(mtcars)
model <- lm(mpg ~ hp, mtcars[1:20, ])
"model"
str(model)

predicted <- predict(model, mtcars[1:20, ], type = "response")
"predicted"
str(predicted)

actual <- mtcars[1:20, "mpg"]
sqrt(mean( (predicted - actual) ^ 2) )
```

```{r}
# Fit lm model: model
model <- lm(price ~ . ,data = diamonds)

# Predict on full data: p
p <- predict(model, diamonds)

# Compute errors: error
error = p  - diamonds$price

# Calculate RMSE
sqrt(mean( error ^ 2))
```

```{r}
# Set seed
set.seed(42)

# Shuffle row indices: rows
rows <- sample(nrow(diamonds))

# Randomly order data
diamonds <- diamonds[rows, ]
```

```{r}
# Determine row to split on: split
split <- round(nrow(diamonds) * 0.80)

# Create train
train <- diamonds[1:split, ]

# Create test
test <- diamonds[(split+1):nrow(diamonds), ]
```

```{r}
# Fit lm model on train: model
model <- lm(price ~ ., data = train)

# Predict on test: p
p <- predict(model, test)
```

```{r}
# Compute errors: error
errors = p - test$price

# Calculate RMSE
sqrt( mean(errors ^ 2) )
```

```{r}
#install.packages("caret")
library(caret)
```

```{r}
# Fit lm model using 10-fold CV: model
model <- train(
  price ~ ., diamonds,
  method = "lm",
  trControl = trainControl(
    method = "cv", number = 10,
    verboseIter = TRUE
  )
)

# Print model to console
model
```

```{r}
# Fit lm model using 5-fold CV: model
model <- train(
  medv ~ ., data = Boston,
  method = "lm",
  trControl = trainControl(
    method = "cv", number = 5,
    verboseIter = TRUE
  )
)

# Print model to console
model
```

```{r}
# Fit lm model using 5 x 5-fold CV: model
model <- train(
  medv ~ ., Boston,
  method = "lm",
  trControl = trainControl(
    method = "cv", number = 5,
    repeats = 5, verboseIter = TRUE
  )
)

# Print model to console
model
```

```{r}
# Predict on full Boston dataset
predict(model, Boston)
```

```{r}
load("~/Documents/Code/R/datacamp/machine learning toolbox/Sonar.RData")
data(Sonar)
```

```{r}
# Get the Sonar data, and many more...

#install.packages("mlbench")
library(mlbench)
```

```{r}
data(Sonar)

# Shuffle row indices: rows
rows = sample(nrow(Sonar))

# Randomly order data: Sonar
Sonar <- Sonar[rows, ]

# Identify row to split on: split
split <- round(nrow(Sonar) * .60)

# Create train
train = Sonar[1:split, ]

# Create test
test = Sonar[(split + 1):nrow(Sonar), ]
```





















