---
title: "Unsupervised Learning"
output: html_notebook
---

```{r}
summary(iris)
plot(Sepal.Length ~ Petal.Width, data = iris)
x <- iris[,c("Sepal.Length", "Petal.Width")]
x
```

```{r}
km.out <- kmeans(x, centers = 3, nstart = 20)
summary(km.out)
km.out$centers
```

This tells us which cluster an observation belongs to:

```{r}
km.out$cluster
```

```{r}
# Scatter plot of x
plot(x,
     col = km.out$cluster,
     main = "k-means with 3 clusters",
     xlab = "",
     ylab = "")
```

```{r}
# Set up 2 x 3 plotting grid
par(mfrow = c(2, 3))

# Set seed
set.seed(1)

for(i in 1:6) {
  # Run kmeans() on x with three clusters and one start
  km.out <- kmeans(x, centers = 3, nstart = 1)
  
  # Plot clusters
  plot(x, col = km.out$cluster, 
       main = km.out$tot.withinss, 
       xlab = "", ylab = "")
}
```

```{r}
# Initialize total within sum of squares error: wss
wss <- 0

# For 1 to 15 cluster centers
for (i in 1:15) {
  km.out <- kmeans(x, centers = i, nstart = 20)
  # Save total within sum of squares to wss variable
  wss[i] <- km.out$tot.withinss
  (summary(km.out))
}
# Plot total within sum of squares vs. number of clusters
plot(1:15, wss, type = "b", 
     xlab = "Number of Clusters", 
     ylab = "Within groups sum of squares")

# Set k equal to the number of clusters corresponding to the elbow location
k <- 1
```

```{r}
# get pokemon data
pokemon <- read.csv("https://assets.datacamp.com/production/course_1815/datasets/Pokemon.csv")

x <- pokemon[, c("HitPoints", "Attack", "Defense", "SpecialAttack", "SpecialDefense", "Speed")]

# Initialize total within sum of squares error: wss
wss <- 0

# For 1 to 15 cluster centers
for (i in 1:15) {
  km.out <- kmeans(x, centers = i, nstart = 20)
  # Save total within sum of squares to wss variable
  wss[i] <- km.out$tot.withinss
}

# Plot total within sum of squares vs. number of clusters
plot(1:15, wss, type = "b", 
     xlab = "Number of Clusters", 
     ylab = "Within groups sum of squares")

# Set k equal to the number of clusters corresponding to the elbow location
# Select number of clusters
k <- 2

# Build model with k clusters: km.out
km.out <- kmeans(x, centers = 2, nstart = 20, iter.max = 50)

# View the resulting model
km.out

# Plot of Defense vs. Speed by cluster membership
plot(x[, c("Defense", "Speed")],
     col = km.out$cluster,
     main = paste("k-means clustering of Pokemon with", k, "clusters"),
     xlab = "Defense", ylab = "Speed")
```






















