---
title: "Unsupervised Learning"
output: html_notebook
---

## Chapter 3 - Principle Components Model

```{r}
# get pokemon data
pokemon <- read.csv("https://assets.datacamp.com/production/course_1815/datasets/Pokemon.csv")

pok <- pokemon[, c("HitPoints", "Attack", "Defense", "SpecialAttack", "SpecialDefense", "Speed")]

# Perform scaled PCA: pr.out
pr.out <- prcomp(pok, scale = TRUE)

# Inspect model output
summary(pr.out)
```

```{r}
# Variability of each principal component: pr.var
pr.var <- pr.out$sdev^2

# Variance explained by each principal component: pve
pve <- pr.var / sum(pr.var)
```

```{r}
# Plot variance explained for each principal component
plot(pve, xlab = "Principal Component",
     ylab = "Proportion of Variance Explained",
     ylim = c(0, 1), type = "b")

# Plot cumulative proportion of variance explained
plot(cumsum(pve), xlab = "Principal Component",
     ylab = "Cumulative Proportion of Variance Explained",
     ylim = c(0, 1), type = "b")
```

```{r}
# Mean of each variable
colMeans(pok)

# Standard deviation of each variable
apply(pok, 2, sd)

# PCA model with scaling: pr.with.scaling
pr.with.scaling <- prcomp(pok, scale = TRUE)

# PCA model without scaling: pr.without.scaling
pr.without.scaling <- prcomp(pok)

# Create biplots of both for comparison
biplot(pr.with.scaling)
biplot(pr.without.scaling)
```









