---
title: "R Notebook"
output: html_notebook
---

# Chapter 2 - Bayesian methods

```{r}
# data prep
rm(list = ls())
#install.packages("naivebayes")
library(naivebayes)
library(tidyverse)

locations <- read_csv("https://assets.datacamp.com/production/course_2906/datasets/locations.csv")

where9am <- locations %>% filter(hour == 9) %>% select(daytype, location)
```


```{r}
# Compute P(A)  P(office)
p_A <- nrow(subset(where9am, location == "office"))/nrow(where9am)
p_A

# Compute P(B) P(weekday)
p_B <- nrow(subset(where9am, daytype == "weekday"))/nrow(where9am)
p_B

# Compute the observed P(A and B) P(office and weekday)
p_AB <- nrow(subset(where9am,
                    daytype == "weekday" &
                      location == "office"))/nrow(where9am)
p_AB

# Compute P(A | B)
p_A_given_B <- p_AB/p_B
p_A_given_B
```

```{r}
# data prep
daytype <- factor(c("weekday", "weekend"))
thursday9am <- data.frame(daytype = daytype[1])
saturday9am <- data.frame(daytype = daytype[2])
```


```{r}
# Load the naivebayes package
library(naivebayes)

# Build the location prediction model
locmodel <- naive_bayes(location ~ daytype, data = where9am)

# Predict Thursday's 9am location
predict(locmodel, thursday9am)

# Predict Saturdays's 9am location
predict(locmodel, saturday9am)
```

```{r}
# The 'naivebayes' package is loaded into the workspace
# and the Naive Bayes 'locmodel' has been built

# Examine the location prediction model
locmodel

# Obtain the predicted probabilities for Thursday at 9am
predict(locmodel, thursday9am , type = "prob")

# Obtain the predicted probabilities for Saturday at 9am
predict(locmodel, saturday9am , type = "prob")
```

```{r}
# data_prep
weekday_afternoon <- locations[13, c(4,6,7)]
weekday_evening <- locations[19, c(4,6,7)]

# The 'naivebayes' package is loaded into the workspace already

# Build a NB model of location
locmodel <- naive_bayes(location ~ daytype + hourtype, data = locations[,c(4,6,7)])

# Predict Brett's location on a weekday afternoon
#predict(locmodel, weekday_afternoon, type = "prob")
predict(locmodel, weekday_afternoon)

# Predict Brett's location on a weekday evening
#predict(locmodel, weekday_evening , type = "prob")
predict(locmodel, weekday_evening)
```

```{r}
# data prep
weekend_afternoon <- locations[85, c(4,6,7)]

# The 'naivebayes' package is loaded into the workspace already
# The Naive Bayes location model (locmodel) has already been built

# Observe the predicted probabilities for a weekend afternoon
predict(locmodel, weekend_afternoon, type = "prob")

# Build a new model using the Laplace correction
locmodel2 <- naive_bayes(location ~ daytype + hourtype,
                         data = locations[,c(4,6,7)],
                         laplace = 1)

# Observe the new predicted probabilities for a weekend afternoon
predict(locmodel2, weekend_afternoon, type = "prob")
```

