---
title: "R Notebook"
output: html_notebook
---

# Chapter 4

```{r}
# data prep
all_loans <- read_csv("https://assets.datacamp.com/production/course_2906/datasets/loans.csv")

loans <- all_loans[which(all_loans$keep == 1), -c(1,2)]
loans$outcome <- factor(loans$default + 1,
                        levels = c(1,2),
                        labels = c("repaid", "default"))
loans <- loans[, -1]

good_credit <- loans %>% 
  filter(loan_amount == "LOW" & 
           emp_length == "10+ years" & 
           home_ownership == "MORTGAGE" & 
           income == "HIGH" & 
           loan_purpose == "major_purchase" & 
           debt_to_income == "AVERAGE" & 
           credit_score == "HIGH" &
           credit_utilization == "LOW" & 
           outcome == "repaid")

bad_credit <- loans %>% 
  filter(loan_amount == "LOW" & 
           emp_length == "6 - 9 years" & 
           home_ownership == "RENT" & 
           income == "MEDIUM" & 
           loan_purpose == "car" & 
           debt_to_income == "LOW" & 
           credit_score == "LOW" &
           credit_utilization == "HIGH" & 
           outcome == "repaid")
```


```{r}
# Load the rpart package
library(rpart)

# Build a lending model predicting loan outcome versus loan amount and credit score
loan_model <- rpart(outcome ~ loan_amount + credit_score,
                    data = loans,
                    method = "class",
                    control = rpart.control(cp = 0))

# Make a prediction for someone with good credit
predict(loan_model, good_credit, type = "class")

# Make a prediction for someone with bad credit
predict(loan_model, bad_credit, type = "class")
```

```{r}
# Examine the loan_model object
loan_model

# Load the rpart.plot package
library(rpart.plot)

# Plot the loan_model with default settings
rpart.plot(loan_model)

# Plot the loan_model with customized settings
rpart.plot(loan_model, type = 3, box.palette = c("red", "green"), fallen.leaves = TRUE)
```

```{r}

# Determine the number of rows for training
train_size <- nrow(loans) * 0.75

# Create a random sample of row IDs
sample_rows <- sample(nrow(loans), train_size)

# Create the training dataset
loans_train <- loans[sample_rows, ]

# Create the test dataset
loans_test <- loans[-sample_rows, ]
```

```{r}
# The 'rpart' package is loaded into the workspace
# The loans_train and loans_test datasets have been created

# Grow a tree using all of the available applicant data
loan_model <- rpart(outcome ~ .,
                    data = loans_train,
                    method = "class",
                    control = rpart.control(cp = 0))

# Make predictions on the test dataset
loans_test$pred <- predict(loan_model,
                           newdata = loans_test,
                           type = "class")

# Examine the confusion matrix
table(loans_test$outcome, loans_test$pred)

# Compute the accuracy on the test dataset
mean(loans_test$outcome == loans_test$pred)
```

```{r}
# The 'rpart' package is loaded into the workspace

# Grow a tree with maxdepth of 6
loan_model <- rpart(outcome ~ .,
                    data = loans_train,
                    method = "class",
                    control =
                      rpart.control(cp = 0, maxdepth = 6))
plotcp(loan_model)

# Compute the accuracy of the simpler tree
loans_test$pred <- predict(loan_model,
                           newdata = loans_test,
                           type = "class")
mean(loans_test$outcome == loans_test$pred)

# Grow a tree with minsplit of 500
loan_model2 <- rpart(outcome ~ .,
                    data = loans_train,
                    method = "class",
                    control = rpart.control(
                      cp = 0,
                      maxdepth = 6,
                      minsplit = 500))
plotcp(loan_model2)

# Compute the accuracy of the simpler tree
loans_test$pred2 <- predict(loan_model2,
                            newdata = loans_test[,-15],
                            type = "class")
mean(loans_test$outcome == loans_test$pred2)
```

