---
title: "R Notebook"
output: html_notebook
---

# Chapter 4

In this sample we where the 80% quartile is on our test test. We then use that to assign no default, or default values. And finally we compare that to the actual rates in our test_set. As ever, our model favours false negatives - i.e. says people will pay when they don't hence an 20% quartile on predictions resulting in a 10% actual default rate in reality.

```{r}
# Make predictions for the probability of default using the pruned tree and the test set.
prob_default_prior <- predict(ptree_prior, newdata = test_set)[ ,2]

# Obtain the cutoff for acceptance rate 80%
cutoff_prior <- quantile(prob_default_prior, 0.8)

# Obtain the binary predictions.
bin_pred_prior_80 <- ifelse(prob_default_prior > cutoff_prior, 1, 0)

# Obtain the actual default status for the accepted loans
accepted_status_prior_80 <- test_set$loan_status[bin_pred_prior_80 == 0]

# Obtain the bad rate for the accepted loans
sum(accepted_status_prior_80 == 1)/length(accepted_status_prior_80)

```

```{r}
# data prep
predictions_loss_matrix <- predict(tree_loss_matrix, newdata = test_set, class = "response")[,2]
```


```{r}
# Have a look at the function strategy_bank
strategy_bank <- function (prob_of_def) {
  cutoff      = rep(NA, 21)
  bad_rate    = rep(NA, 21)
  accept_rate = seq(1 ,0, by=-0.05)

  for (i in 1:21) {
    cutoff[i] = quantile(prob_of_def, accept_rate[i])
    pred_i = ifelse(prob_of_def> cutoff[i], 1, 0)
    pred_as_good = test_set$loan_status[pred_i==0]
    bad_rate[i] = sum(pred_as_good) / length(pred_as_good)
  }
  table = cbind(accept_rate,
                cutoff = round(cutoff,4),
                bad_rate = round(bad_rate,4))
  return(list(table       = table,
              bad_rate    = bad_rate,
              accept_rate = accept_rate,
              cutoff      = cutoff))
}

# Apply the function strategy_bank to both predictions_cloglog and predictions_loss_matrix
strategy_cloglog <- strategy_bank(predictions_cloglog)
strategy_loss_matrix <- strategy_bank(predictions_loss_matrix)

# Obtain the strategy tables for both prediction-vectors
strategy_cloglog$table
strategy_loss_matrix$table

# Plot the strategy functions
par(mfrow = c(1,2))
plot(strategy_cloglog$accept_rate, strategy_cloglog$bad_rate, 
     type = "l", xlab = "Acceptance rate", ylab = "Bad rate", 
     lwd = 2, main = "logistic regression")

plot(strategy_loss_matrix$accept_rate, strategy_loss_matrix$bad_rate, 
     type = "l", xlab = "Acceptance rate", 
     ylab = "Bad rate", lwd = 2, main = "tree")
```

```{r}
# Load the pROC-package
library(pROC)

# Construct the objects containing ROC-information
ROC_logit    <- roc(test_set$loan_status, predictions_logit)
ROC_probit   <- roc(test_set$loan_status, predictions_probit)
ROC_cloglog  <- roc(test_set$loan_status, predictions_cloglog)
ROC_all_full <- roc(test_set$loan_status, predictions_all_full)

# Draw all ROCs on one plot
plot(ROC_logit)
lines(ROC_probit, col = "blue")
lines(ROC_cloglog, col = "red")
lines(ROC_all_full, col = "green")

# Compute the AUCs
auc(ROC_logit)
auc(ROC_probit)
auc(ROC_cloglog)
auc(ROC_all_full)
```

```{r}
# data prep
predictions_undersample <- predict(tree_undersample, class = "response", newdata = test_set)[,2]
predictions_prior <- predict(tree_prior, class = "response", newdata = test_set)[,2]
predictions_weights <- predict(tree_weights, class = "response", newdata = test_set)[,2]
```


```{r}
# Construct the objects containing ROC-information
ROC_undersample <- roc(test_set$loan_status, predictions_undersample)
ROC_prior <-roc(test_set$loan_status, predictions_prior)
ROC_loss_matrix <- roc(test_set$loan_status, predictions_loss_matrix)
ROC_weights <- roc(test_set$loan_status, predictions_weights)

# Draw the ROC-curves in one plot
plot(ROC_undersample)
lines(ROC_prior, col = "blue")
lines(ROC_loss_matrix, col = "red")
lines(ROC_weights, col = "green")

# Compute the AUCs
auc(ROC_undersample)
auc(ROC_prior)
auc(ROC_loss_matrix)
auc(ROC_weights)
```




