---
title: "R Notebook"
output: html_notebook
---

# Chapter 4 notes


```{r}
# prep data
data <- read.zoo(file = "https://assets.datacamp.com/production/course_2300/datasets/data_4_1.csv",
                 format = "%Y-%m-%d",
                 sep = ',',
                 index.column = 1,
                 skip = 1)
colnames(data) <- c("value", "return")

# used in later exercise
portfolio <- data$return
```

```{r}
# Plot the portfolio value
plot(data$value, main = "Portfolio Value")

# Plot the portfolio return
plot(data$return, main = "Portfolio Return")

# Plot a histogram of portfolio return 
hist(data$return, probability = TRUE)

# Add a density line
lines(density(data$return), col = "red", lwd = 2)
```

```{r}
# prep data
data <- read.zoo(file = "https://assets.datacamp.com/production/course_2300/datasets/data_4_3.csv",
                 format = "%Y-%m-%d",
                 sep = ',',
                 index.column = 1,
                 skip = 1)
colnames(data) <- c("GS","KO","DIS","CAT")
```

```{r}
# Plot the four stocks on the same graphical window
par(mfrow = c(2,2), mex = 0.8, cex = 0.8)
plot(data$GS)
plot(data$KO)
plot(data$DIS)
plot(data$CAT)
```

```{r}
# data prep
gs  <- na.trim(ROC(data$GS))
ko  <- na.trim(ROC(data$KO))
dis <- na.trim(ROC(data$DIS))
cat <- na.trim(ROC(data$CAT))
```

```{r}
# Draw the scatterplot of gs against the portfolio
plot(portfolio, gs)

# Add a regression line in red
abline(reg = lm(portfolio ~ gs), col = "red", lwd = 2)

# Plot scatterplots and regression lines to a 2x2 window
par(mfrow = c(2,2))
plot(gs, portfolio)
abline(reg = lm(portfolio ~ gs), col = "red", lwd = 2)
plot(ko, portfolio)
abline(reg = lm(portfolio ~ ko), col = "red", lwd = 2)
plot(dis, portfolio)
abline(reg = lm(portfolio ~ dis), col = "red", lwd = 2)
plot(cat, portfolio)
abline(reg = lm(portfolio ~ cat), col = "red", lwd = 2)

# Clever code.. doens't pass test 'tsk
for (stock in list(gs, ko, dis, cat)) { 
  plot(portfolio, stock)
  abline(reg = lm(portfolio ~ stock), col = "red", lwd = 2)
}
```

```{r}
# data prep
old.vs.new.portfolio <- read.zoo(file = "https://assets.datacamp.com/production/course_2300/datasets/old.vs.new.portfolio.csv",
                 format = "%Y-%m-%d",
                 sep = ',',
                 index.column = 1,
                 skip = 1)
colnames(old.vs.new.portfolio) <- c("old.portfolio.value","new.portfolio.value","old.portfolio.rtn","new.portfolio.rtn")
```

```{r}
# Plot new and old portfolio values on same chart
plot(old.vs.new.portfolio$old.portfolio.value)
lines(old.vs.new.portfolio$new.portfolio.value, col = "red")

# Plot density of the new and old portfolio returns on same chart
plot(density(old.vs.new.portfolio$old.portfolio.rtn))
lines(density(old.vs.new.portfolio$new.portfolio.rtn), col = "red")
```

```{r}
# Draw value, return, drawdowns of old portfolio
charts.PerformanceSummary(old.vs.new.portfolio$old.portfolio.rtn)

# Draw value, return, drawdowns of new portfolio
charts.PerformanceSummary(old.vs.new.portfolio$new.portfolio.rtn)

# Draw both portfolios on same chart
charts.PerformanceSummary(old.vs.new.portfolio[ ,c("old.portfolio.rtn", "new.portfolio.rtn")])
```

