---
title: "R Notebook"
output: html_notebook
---

# Chapter 1

```{r}
library(data.table)
# The data.table package is preloaded

# Create my_first_data_table
my_first_data_table <- data.table(x = c("a", "b", "c", "d", "e"), 
                                  y = c(1, 2, 3, 4, 5))  
  
# Create a data.table using recycling
DT <- data.table(a = c(1L, 2L), b = LETTERS[1:4])

# Print the third row to the console
DT[3,]

# Print the second and third row to the console without using commas
DT[2:3]
```

```{r}
# DT and the data.table package are pre-loaded

# Print the second to last row of DT using .N
DT[.N-1]

# Print the column names of DT
names(DT)

# Print the number or rows and columns of DT
dim(DT)

# Print a new data.table containing rows 2, 2, and 3 of DT
DT[c(2,2,3)]
```

```{r}
# data prep
DT = data.table(A = 1L:5L,
                B = letters[1:5],
                C = 6L:10L)

# DT and the data.table package are pre-loaded

# Subset rows 1 and 3, and columns B and C
DT[c(1,3), .(B, C)]

# Assign to ans the correct value
ans <- DT[ , .(B, val = A * C)]
  
# Fill in the blanks such that ans2 equals target
target <- data.table(B = c("a", "b", "c", "d", "e", 
                           "a", "b", "c", "d", "e"), 
                     val = as.integer(c(6:10, 1:5)))
ans2 <- DT[, .(B, val = as.integer(c(6:10, 1:5)))]
```

```{r}
# iris is already available in your workspace

# Convert iris to a data.table: DT
DT <- data.table(iris)

# For each Species, print the mean Sepal.Length
DT[ ,
    mean(Sepal.Length),
    by = Species]

# Print mean Sepal.Length, grouping by first letter of Species
DT[ ,
    mean(Sepal.Length),
    by = substr(Species, 1, 1)]
```

```{r}
# data.table version of iris: DT
DT <- as.data.table(iris)

# Group the specimens by Sepal area (to the nearest 10 cm2) and count how many occur in each group
DT[, .N, by = 10 * round(Sepal.Length * Sepal.Width / 10)]

# Now name the output columns `Area` and `Count`
DT[ ,
    .(Count = .N),
    by = .(Area = 10 * round(Sepal.Length * Sepal.Width / 10))]
```

```{r}
# Create the data.table DT
DT <- data.table(A = rep(letters[2:1], each = 4L), 
                 B = rep(1:4, each = 2L), 
                 C = sample(8))

# Create the new data.table, DT2
DT2 <- DT[,
          .(C = cumsum(C)),
          by = .(A, B)]

# Select from DT2 the last two values from C while you group by A
DT2[ ,
   .(C = tail(C, 2)),
   by = .(A)]
```

