---
title: "R Notebook"
output: html_notebook
---

# Chapter 2

```{r}
# The data.table package has already been loaded

# Build DT
DT <- data.table(A = rep(letters[2:1], each = 4L), 
                 B = rep(1:4, each = 2L), 
                 C = sample(8)) 

# Combine the two steps in a one-liner
DT2 <- DT[, .(C = cumsum(C)), by = .(A, B)]
DT2[, .(C = tail(C, 2)), by = A]

DT[, .(C = cumsum(C)), by = .(A, B)][, .(C = tail(C, 2)), by = A]
```

```{r}
DT <- data.table(iris)
# The data.table DT is loaded in your workspace

# Perform chained operations on DT
DT[, .(Sepal.Length = median(Sepal.Length), 
       Sepal.Width  = median(Sepal.Width), 
       Petal.Length = median(Petal.Length),
       Petal.Width  = median(Petal.Width)), 
   by = Species][order(-Species)]

# numerical minus works on order here because species is a factor.
# This just so happens to be enumerated in alphabetical order
```

```{r}
# A new data.table DT is available

# Mean of columns
DT[, lapply(.SD, mean), by = Species]

# Median of columns
DT[, lapply(.SD, median), by = Species][order(-Species)]
```

```{r}
# data prep
DT <- data.table(
  grp = c(6,6,8,8,8),
  Q1  = c(5,3,1,2,4),
  Q2  = c(1,3,2,1,3),
  Q3  = c(4,5,1,2,4),
  H1  = c(5,4,2,1,5),
  H2  = c(2,2,3,4,3)
)
# A new data.table DT is available

# Calculate the sum of the Q columns
DT[, lapply(.SD, sum), .SDcols = 2:4]

# Calculate the sum of columns H1 and H2 
DT[, lapply(.SD, sum), .SDcols = paste0("H", 1:2)]

# Select all but the first row of groups 1 and 2, returning only the grp column and the Q columns
DT[, .SD[-1], by = grp, .SDcols = paste0("Q", 1:3)]
```

```{r}
# example
#dogs[, lapply(.SD, mean), by = sex, .SDcols = c("weight", "age")]

# data prep
DT <- data.table(x = c(2,1,2,1,2,2,1),
                 y = c(1,3,5,7,9,11,13),
                 z = c(2,4,6,8,10,12,14))

# DT is pre-loaded

# Sum of all columns and the number of rows
DT[,
   c(lapply(.SD, sum), .N),
   by = x,
   .SDcols = c("x","y","z")]

# Cumulative sum of column x and y while grouping by x and z > 8
DT[,
   lapply(.SD, cumsum),
   by = .(by1 = x, by2 = y>8),
   .SDcols = c("x","y")]
```

```{r}
# The data.table DT
DT <- data.table(A = letters[c(1, 1, 1, 2, 2)], B = 1:5)

# Add column by reference: Total
DT[, Total := sum(B), by = A]

# Add 1 to column B
DT[c(2, 4), B := B + 1L]

# Add a new column Total2
DT[2:4, Total2 := sum(B), by = A]

# Remove the Total column
DT[, Total := NULL]

# Select the third column using `[[`
DT[[3]]
```

```{r}
# A data.table DT has been created for you
DT <- data.table(A = c(1, 1, 1, 2, 2), B = 1:5)

# Update B, add C and D
DT[,
   `:=`(B = B + 1,
        C = A + B,
        D = 2)]

# Delete my_cols
my_cols <- c("B", "C")
DT[, (my_cols) := NULL]

# Delete column 2 by number
DT[, 2 := NULL]
```

```{r}
# data prep
DT <- data.table(
  A = c(2,2,3,5,2,5,5,4,4,1),
  B = c(2,1,4,2,4,3,4,5,2,4),
  C = c(5,2,4,1,2,2,1,2,5,2),
  D = c(3,3,3,1,5,4,4,1,4,3)
)

# Set the seed
set.seed(1)

# Check the DT that is made available to you
DT

# For loop with set
for (j in c(2,3,4)) set(DT, sample(1:nrow(DT), 3), j, NA) 

# Change the column names to lowercase
setnames(DT, names(DT), tolower(names(DT)))

# Print the resulting DT to the console
DT
```

```{r}
# Define DT
DT <- data.table(a = letters[c(1, 1, 1, 2, 2)], b = 1)

# Add a suffix "_2" to all column names


# Change column name "a_2" to "A2"


# Reverse the order of the columns

```

