---
title: "Chapter 2"
output: html_notebook
---

```{r}
# P(T < 3) for df = 10
(x <- pt(3, lower.tail = T, df = 10))

# P(T > 3) for df = 10
(y <- pt(3, lower.tail = F, df = 10))

# P(T > 3) for df = 100
(z <- pt(3, lower.tail = F, df=100))

# Comparison
y == z
y > z
y < z
```

```{r}
samps = 1000
td_10  <- data.frame('val' = rt(n=samps, df=10), 'deg'=10)
td_100 <- data.frame('val' = rt(n=samps, df=100), 'deg'=100)
sum(td_10$val > 3)/samps
sum(td_100$val > 3)/samps

hist(td_10$val, col='skyblue', breaks=100)
hist(td_100$val, add=T, col='red', breaks=100)
```

```{r}
# 95th percentile for df = 10
(x <- qt(0.95, df = 10))

# upper bound of middle 95th percent for df = 10
(y <- qt(0.975, df=10))

# upper bound of middle 95th percent for df = 100
(z <- qt(0.975, df=100))

# Comparison
y == z
y > z
y < z
```

```{r}
# data prep
require(openintro)
data("acs12")
summary(acs12)
```

```{r}
# Subset for employed respondents
acs12_emp <- acs12 %>%
  filter(employment == 'employed')

# Construct 95% CI for avg time_to_work
t.test(acs12_emp$time_to_work, conf.level = 0.95)
```

```{r}
t.test(acs12_emp$hrs_work, conf.level = 0.95)
```

```{r}
# data prep
data("textbooks")
str(textbooks)
```

```{r}
# 90% CI
t.test(textbooks$diff, conf.level = 0.90)

# 95% CI
t.test(textbooks$diff, conf.level = 0.95)

# 99% CI
t.test(textbooks$diff, conf.level = 0.99)
```

```{r}
# Calculate diff
textbooks <- textbooks %>%
  mutate(diff = uclaNew - amazNew)

# Conduct HT
t.test(textbooks$diff, mu=0, alternative = 'two.sided')
```

```{r}
# Calculate 15000 bootstrap medians
textdiff_med_ci <- textbooks %>%
  specify(response = 'diff') %>%
  generate(reps=15000, type = 'bootstrap') %>%
  calculate(stat='median')
  
# Calculate the 95% CI via percentile method
textdiff_med_ci %>%
  summarize(l = quantile(stat, 0.025),
            u = quantile(stat, 0.975))
```

```{r}
data("hsb2")
str(hsb2)
```



```{r}
data("hsb2")

# Calculate diff
hsb2 <- hsb2 %>%
  mutate(diff = math - science)
  
# Generate 15000 bootstrap medians centered at null
scorediff_med_ht <- hsb2 %>%
  specify(response = diff) %>%
  hypothesize(null = 'point', med=0) %>% 
  generate(reps=15000, type='bootstrap') %>% 
  calculate('median')
  
# Calculate observed median of differences
scorediff_med_obs <- hsb2 %>%
  summarize(median(diff)) %>%
  pull()

# Calculate p-value
scorediff_med_ht %>%
  filter(stat > scorediff_med_obs) %>%
  summarize(p_val = 2 * n() / 15000)
```



















